name=Soldered I2S Digital Audio Amplifier Arduino Library
version=1.0.0
author=Soldered
maintainer=Soldered <soldered@soldered.com>
sentence=Soldered Arduino library for I2S Digital Audio Amplifier
paragraph=Arduino library for I2S Digital Audio Amplifier
category=Other
url=https://solde.red/333355
repository=https://github.com/SolderedElectronics/Soldered-I2S-Audio-Amplifier-Arduino-Library
architectures=*
includes=Soldered_I2S_Audio_Amplifier.h
